### PR TITLE
Quickstart tutorial

### PR DESCRIPTION
**Pull request by chrizandr**
Changelog by commits:
* Created Quickstart Guide.

* typo fixed

* update quickstart.md

* Custom API Documentation section added.

* Font size fix

* custom API Doc removed.

* Added required changes.

* typo fixed.

We can have discussion about the changes to this branch over here.

Linking old PR for reference #5

### CODE REVIEW

**Comment by chrizandr** [comment]
Give a whole run through with the Movie example using core, hydrus, agent and agent GUI.

**Comment by Purvanshsingh** [comment]
@chrizandr Sure, I was also thinking to add the agent, but I have a concern as we have already explained in the setup of hydrus & creating API doc using core. should we repeat the same in Quickstart?

**Comment by Purvanshsingh** [comment]
The docker implementation of agent is on hold due to this [issue](https://github.com/HTTP-APIs/hydra-python-agent/issues/104#issuecomment-497381440).

**Comment by Purvanshsingh** [comment]
The docker implementation of agent is on hold due to this [issue](https://github.com/HTTP-APIs/hydra-python-agent/issues/104#issuecomment-497381440).

**Pull request merged**
